services:
  app:
    image: crpi-995uocus6og9mdf4.cn-beijing.personal.cr.aliyuncs.com/wuwenlong797/ron-blog-node:latest  # 使用阿里云上传的 Node.js 镜像
    ports:
      - "3000:3000" # 将容器内的 3000 端口映射到主机的 3000 端口
    volumes:
      - /var/docker/public:/app/public
    command: >
      sh -c "
      [ ! -d /app/public ] && cp -r /app/public/* /var/docker/public || true &&
      node index.js
      "
    environment:
      - MONGO_URI=mongodb://mongo:27017/ronBlog # MongoDB 地址
    depends_on:
      - mongo # 等待 MongoDB 启动

  mongo:
    image: crpi-995uocus6og9mdf4.cn-beijing.personal.cr.aliyuncs.com/wuwenlong797/mongo:latest  # 使用阿里云上传的 MongoDB 镜像
    container_name: ron-blog-mongo
    ports:
      - "27017:27017" # 映射 MongoDB 默认端口
    volumes:
      - ./data/db:/data/db # 持久化 MongoDB 数据