services:
  app:
    image: crpi-995uocus6og9mdf4.cn-beijing.personal.cr.aliyuncs.com/wuwenlong797/ron-blog-node:latest
    ports:
      - "3000:3000"
    volumes:
      - ./dist/:/usr/src/app
      - ./data/public:/public
    environment:
      - MONGO_URI=mongodb://mongo:27017/ronBlog
      - REDIS_HOST=redis  # 添加 Redis 连接信息
      - REDIS_PORT=6379
    depends_on:
      - mongo
      - redis  # 依赖 Redis 启动
    working_dir: /usr/src/app
    command: bash -c "mkdir -p /public && node index.js"
  mongo:
    image: crpi-995uocus6og9mdf4.cn-beijing.personal.cr.aliyuncs.com/wuwenlong797/mongo:latest
    container_name: ron-blog-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root  # 设置 root 用户名
      - MONGO_INITDB_ROOT_PASSWORD=wu04270018  # 设置 root 密码
    command: mongod --auth  # 启用认证
  redis:
    image: redis:latest
    container_name: ron-blog-redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data  # 持久化 Redis 数据
    command: redis-server --appendonly yes  # 启用持久化 AOF